name: PR Notification to Slack

on:
  pull_request:
    types:
      - opened
      - closed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send PR notification to Slack
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        PR_TITLE=$(jq --raw-output .pull_request.title $GITHUB_EVENT_PATH)
        PR_URL=$(jq --raw-output .pull_request.html_url $GITHUB_EVENT_PATH)
        AUTHOR=$(jq --raw-output .pull_request.user.login $GITHUB_EVENT_PATH)
        STATE=$(jq --raw-output .pull_request.state $GITHUB_EVENT_PATH)
        MERGED=$(jq --raw-output .pull_request.merged $GITHUB_EVENT_PATH)

        if [[ "$STATE" == "opened" ]]; then
          STATUS="opened"
          COLOR="#36a64f"  # Green for opened PR
        elif [[ "$STATE" == "closed" && "$MERGED" == "true" ]]; then
          STATUS="merged"
          COLOR="#00bcd4"  # Blue for merged PR
        else
          exit 0  # Skip if PR is closed but not merged
        fi

        curl -X POST -H 'Content-type: application/json' --data "{
          \"blocks\": [
            {
              \"type\": \"section\",
              \"block_id\": \"pr_notification\",
              \"text\": {
                \"type\": \"mrkdwn\",
                \"text\": \"*PR $STATUS:* <$PR_URL|$PR_TITLE>\nBy: $AUTHOR\"
              },
              \"accessory\": {
                \"type\": \"divider\"
              }
            },
            {
              \"type\": \"section\",
              \"text\": {
                \"type\": \"mrkdwn\",
                \"text\": \"*Status:* $STATUS\n*Author:* $AUTHOR\"
              },
              \"color\": \"$COLOR\"
            }
          ]
        }" $SLACK_WEBHOOK_URL
